// Scans public/images/mentors/ and generates src/data/mentors.generated.ts.
// Filename format: "<order>-<Name>-<Role>.<ext>", e.g. "01-John Robins-Physical AI.png".
// Runs automatically before `dev`/`build` (see package.json) so dropping a
// correctly-named photo in the folder is enough to update the About page —
// no code changes needed.
import { readdirSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const mentorsDir = path.join(root, "public/images/mentors");
const outFile = path.join(root, "src/data/mentors.generated.ts");

const FILENAME_PATTERN = /^(\d+)-(.+?)-(.+)\.(png|jpg|jpeg|webp)$/i;

function parseMentorFile(filename) {
  const match = FILENAME_PATTERN.exec(filename);
  if (!match) return null;
  const [, order, name, role] = match;
  return {
    order: Number(order),
    name: name.trim(),
    role: role.trim(),
    image: `/images/mentors/${encodeURIComponent(filename)}`,
  };
}

let entries;
try {
  entries = readdirSync(mentorsDir);
} catch {
  entries = [];
}

const mentors = [];
const skipped = [];

for (const filename of entries) {
  if (filename.startsWith(".")) continue;
  const mentor = parseMentorFile(filename);
  if (mentor) {
    mentors.push(mentor);
  } else {
    skipped.push(filename);
  }
}

mentors.sort((a, b) => a.order - b.order);

if (skipped.length > 0) {
  console.warn(
    `[generate-mentors] Skipped ${skipped.length} file(s) in public/images/mentors that ` +
      `don't match "<order>-<Name>-<Role>.<ext>": ${skipped.join(", ")}`
  );
}

const banner =
  "// AUTO-GENERATED by scripts/generate-mentors.mjs — do not edit by hand.\n" +
  "// Add, rename, or remove files in public/images/mentors/ instead, then\n" +
  "// re-run `npm run dev` or `npm run build` to regenerate this file.\n";

const body =
  `export interface Mentor {\n` +
  `  name: string;\n` +
  `  role: string;\n` +
  `  image: string;\n` +
  `}\n\n` +
  `export const mentors: Mentor[] = ${JSON.stringify(
    mentors.map(({ name, role, image }) => ({ name, role, image })),
    null,
    2
  )};\n`;

mkdirSync(path.dirname(outFile), { recursive: true });
writeFileSync(outFile, banner + "\n" + body);

console.log(`[generate-mentors] Wrote ${mentors.length} mentor(s) to src/data/mentors.generated.ts`);
